# Зертханалық жұмыстар: Шешім ағаштары

Бұл жаттығуда сіз шешім ағашын нөлден бастап жүзеге асырасыз және оны саңырауқұлақтың жеуге жарамды немесе улы екенін жіктеу тапсырмасына қолданасыз.

# 1- Қажетті кітапханалар

Алдымен, осы тапсырма кезінде қажет болатын барлық бумаларды импорттау үшін төмендегі ұяшықты іске қосайық.

* numpy - Python-да матрицалармен жұмыс істеуге арналған негізгі пакет.
* matplotlib - бұл Python тілінде графиктерді салуға арналған әйгілі кітапхана.
* public_tests осы тапсырма үшін көмекші функцияларды қамтиды. Бұл файлдағы кодты өзгерту қажет емес.




In [1]:
import numpy as np
import matplotlib.pyplot as plt
from public_tests import *

%matplotlib inline

## 2 - Мәселе туралы мәлімдеме

Сіз жабайы саңырауқұлақтарды өсіретін және сататын компанияны ашып жатырсыз делік.

- Саңырауқұлақтардың барлығы жеуге жарамсыз болғандықтан, сіз оның физикалық қасиеттеріне қарай оның жеуге жарамды немесе улы екенін анықтағыңыз келеді.
- Сізде осы тапсырма үшін пайдалануға болатын кейбір деректер бар.

Қандай саңырауқұлақтарды қауіпсіз сатуға болатынын анықтау үшін деректерді пайдалана аласыз ба?

Ескертпе: Пайдаланылған деректер жиыны тек көрнекі мақсаттарға арналған. Бұл жеуге болатын саңырауқұлақтарды анықтауға арналған нұсқаулық емес.



## 3 - Dataset

Осы тапсырма үшін деректер жинағын жүктеу арқылы бастайсыз. Сіз жинаған деректер жинағы келесідей:

| Cap Color | Stalk Shape | Solitary | Edible |
|:---------:|:-----------:|:--------:|:------:|
|   Brown   |   Tapering  |    Yes   |    1   |
|   Brown   |  Enlarging  |    Yes   |    1   |
|   Brown   |  Enlarging  |    No    |    0   |
|   Brown   |  Enlarging  |    No    |    0   |
|   Brown   |   Tapering  |    Yes   |    1   |
|    Red    |   Tapering  |    Yes   |    0   |
|    Red    |  Enlarging  |    No    |    0   |
|   Brown   |  Enlarging  |    Yes   |    1   |
|    Red    |   Tapering  |    No    |    1   |
|   Brown   |  Enlarging  |    No    |    0   |


- Сізде саңырауқұлақтардың 10 мысалы бар. Әрбір мысал үшін сізде бар
  - Үш ерекшелік
        - Cap Color (`Brown` or `Red`),
        - Stalk Shape (`Tapering` or `Enlarging`), and
        - Solitary (`Yes` or `No`)

<a name="3.1"></a>
### 3.1 One hot кодталған деректер жинағы
Іске асырудың қарапайымдылығы үшін бізде мүмкіндіктер бір реттік кодталған (оларды 0 немесе 1 құнды мүмкіндіктерге айналдырдық)

| Brown Cap | Tapering Stalk Shape | Solitary | Edible |
|:---------:|:--------------------:|:--------:|:------:|
|     1     |           1          |     1    |    1   |
|     1     |           0          |     1    |    1   |
|     1     |           0          |     0    |    0   |
|     1     |           0          |     0    |    0   |
|     1     |           1          |     1    |    1   |
|     0     |           1          |     1    |    0   |
|     0     |           0          |     0    |    0   |
|     1     |           0          |     1    |    1   |
|     0     |           1          |     0    |    1   |
|     1     |           0          |     0    |    0   |

Сондықтан,

- `X_train` әр мысал үшін үш белгіден (feature) тұрады:  
  - Brown Color (`1` мәні қалпақ түсінің "Brown" екенін, ал `0` мәні "Red" екенін білдіреді)  
  - Tapering Shape (`1` мәні саңырауқұлақ сабағының "Tapering" (жіңішкеретін) пішінін, ал `0` мәні "Enlarging" (кеңейетін) пішінін білдіреді)  
  - Solitary (`1` мәні "Иә" дегенді, ал `0` мәні "Жоқ" дегенді білдіреді)

- `y_train` саңырауқұлақтың жеуге жарамды-жарамсыз екенін көрсетеді:  
  - `y = 1` саңырауқұлақ жеуге жарамды екенін білдіреді  
  - `y = 0` саңырауқұлақ улы екенін білдіреді

In [2]:
X_train = np.array([[1,1,1],[1,0,1],[1,0,0],[1,0,0],[1,1,1],[0,1,1],[0,0,0],[1,0,1],[0,1,0],[1,0,0]])
y_train = np.array([1,1,0,0,1,0,0,1,1,0])

#### Айнымалыларды қарау  
Деректер жинағыңызбен жақсырақ танысу үшін ең тиімді әдістердің бірі – әрбір айнымалыны басып шығарып, оның қандай деректерді қамтитынын тексеру.

Төмендегі код `X_train` айнымалысының алғашқы бірнеше элементін және оның түрін (type) басып шығарады:

In [3]:
print("X_train алғашқы бірнеше элементтері:\n", X_train[:5])
print("X_trainның дерек түрі:",type(X_train))

X_train алғашқы бірнеше элементтері:
 [[1 1 1]
 [1 0 1]
 [1 0 0]
 [1 0 0]
 [1 1 1]]
X_trainның дерек түрі: <class 'numpy.ndarray'>


Енді «y_train» үшін де солай істейік

In [4]:
print("X_train алғашқы бірнеше элементтері", y_train[:5])
print("y_train дерек түрі:",type(y_train))

X_train алғашқы бірнеше элементтері [1 1 0 0 1]
y_train дерек түрі: <class 'numpy.ndarray'>


#### Check the dimensions of your variables

Another useful way to get familiar with your data is to view its dimensions.

Please print the shape of `X_train` and `y_train` and see how many training examples you have in your dataset.

In [5]:
print('X_train өлшемі:', X_train.shape)
print('y_train өлшемі:', y_train.shape)
print('Жаттығу жиынтығындағы мысалдар саны (m):', len(X_train))

X_train өлшемі: (10, 3)
y_train өлшемі: (10,)
Жаттығу жиынтығындағы мысалдар саны (m): 10


## 4 - Decision Tree Қайталама

Осы практикалық жұмыста сіз берілген деректер жиынтығы негізінде шешім ағашын құрасыз.

### Шешім ағашын құру қадамдары:

1. **Тамыр түйінінен (root node) бастау:**  
   Барлық мысалдар тамыр түйінінде болады.

2. **Ақпараттық ұтысты (Information Gain) есептеу:**  
   Барлық мүмкін белгілер бойынша ақпараттық ұтысты есептеп, ең үлкен ұтыс беретін белгіні таңдау.

3. **Деректер жиынын бөлу:**  
   Таңдалған белгі бойынша деректерді бөліп, ағаштың сол және оң тармақтарын (left and right branches) құру.

4. **Бөлуді қайталау:**  
   Тоқтату критерийі орындалғанға дейін бөлуді қайталай беру.

---

### Осы лабораториялық жұмыста сіз келесі функцияларды жүзеге асырасыз:

- **Энтропияны есептеу:**  
  Белгілі бір түйіндегі энтропияны есептейді.

- **Деректер жиынын бөлу:**  
  Белгілі бір түйінде берілген белгіге байланысты деректерді сол және оң тармақтарға бөледі.

- **Ақпараттық ұтысты есептеу:**  
  Берілген белгі бойынша бөлуден алынған ақпараттық ұтысты есептейді.

- **Ең үлкен ақпараттық ұтыс беретін белгіні таңдау:**  
  Жиынтыдағы барлық белгілер арасында ең тиімдісін анықтайды.

---

### Шешім ағашын құру:

Сіз жасаған көмекші функцияларды пайдаланып, шешім ағашын құрасыз. Бөлуді тоқтату критерийі ретінде біз ағаштың максималды тереңдігін 2-ге орнатамыз.

###  Энтропияны есептеу

Ең алдымен, сіз түйінде энтропияны (ласушылықтың өлшемі) есептейтін `compute_entropy` деп аталатын көмекші функция жазасыз.
- Функция numpy массивін (`y`) аргумент ретінде қабылдайды, онда түйіндегі үлгілер жеуге жарамды (`1`) немесе уланған (`0`) екенін көрсетеді.

Төмендегі `compute_entropy()` функциясын келесі нұсқауларға сәйкес толықтырыңыз:
* Жеге жарамды үлгілердің үлесін ($p_1$) есептеңіз (яғни, `y` массивіндегі мәні `1` болатын үлгілердің үлесі)
* Энтропия келесі формула бойынша есептеледі

$$H(p_1) = -p_1 \text{log}_2(p_1) - (1- p_1) \text{log}_2(1- p_1)$$
* Ескерту:
    * Логарифм негізі $2$-ге тең
    * Реализация барысында, $0\text{log}_2(0) = 0$ деп есептеледі. Яғни, егер `p_1 = 0` немесе `p_1 = 1` болса, энтропияны `0` деп орнатыңыз
    * Түйіндегі деректер бос емес екеніне (яғни, `len(y) != 0`) көз жеткізіңіз. Егер бос болса, `0` қайтарыңыз

<a name="ex01"></a>
### 1-ші Тапсырма

Алдыңғы нұсқауларға сүйене отырып, `compute_entropy()` функциясын толықтырыңыз.

Егер қиындық туындаса, келесі ұяшықтан кейін берілген кеңестерді қарап, іске асыруға көмек алыңыз.

In [6]:
def compute_entropy(y):
    """
    Энтропияны есептейді

    Параметрлер:
       y (ndarray): Әрбір үлгінің түйінде жеуге жарамды (`1`) немесе уланған (`0`) екенін көрсететін numpy массиві

    Қайтарылатын мән:
        entropy (float): Түйіндегі энтропия

    """
    # Төмендегі айнымалыларды дұрыс қайтаруыңыз қажет
    entropy = 0.

    ### КОДТЫ ОСЫ ЖЕРДЕ БАСТАҢЫЗ ###


    ### КОДТЫ ОСЫ ЖЕРДЕ АЯҚТАҢЫЗ ###

    return entropy


Келесі сынақ кодын іске қосу арқылы іске асырудың дұрыстығын тексеруге болады:

In [7]:
# Compute entropy at the root node (i.e. with all examples)
# Since we have 5 edible and 5 non-edible mushrooms, the entropy should be 1"

print("Түбірлік түйіндегі энтропия: ", compute_entropy(y_train))

# UNIT TESTS
compute_entropy_test(compute_entropy)

Түбірлік түйіндегі энтропия:  1.0
 All tests passed.


<a name="4.2"></a>
### 4.2  Деректер жиынын бөлу

Келесі қадамда, сіз түйіндегі деректер мен бөлінетін ерекшелікті қабылдайтын, содан кейін оны сол және оң тармақтарға бөлетін `split_dataset` деп аталатын көмекші функция жазасыз. Кейінірек, лабораторияда сіз бөлудің қаншалықты жақсы екенін есептеу үшін кодты жүзеге асырасыз.

- Функция түйіндегі деректердің индекс тізімін, оқыту деректерін және бөлінетін ерекшелікті (feature) қабылдайды.
- Ол деректерді бөледі және сол және оң тармақтағы индекстердің жиынын қайтарады.
- Мысалы, түбір түйіннен бастайық делік (яғни, `node_indices = [0,1,2,3,4,5,6,7,8,9]`), және біз ерекшелік ретінде мысалының қоңыр қалпағының бар-жоғын (1 — бар, 0 — жоқ) қолданамыз.
    - Функцияның нәтижесінде, `left_indices = [0,1,2,3,4,7,9]` және `right_indices = [5,6,8]` болады.
    
| Индекс | Қоңыр Қалпақ | Шырайлы Соққының Пішіні | Жалғыз | Жеміс   |
|:------:|:------------:|:----------------------:|:------:|:------:|
|   0    |      1       |           1            |    1   |   1    |
|   1    |      1       |           0            |    1   |   1    |
|   2    |      1       |           0            |    0   |   0    |
|   3    |      1       |           0            |    0   |   0    |
|   4    |      1       |           1            |    1   |   1    |
|   5    |      0       |           1            |    1   |   0    |
|   6    |      0       |           0            |    0   |   0    |
|   7    |      1       |           0            |    1   |   1    |
|   8    |      0       |           1            |    0   |   1    |
|   9    |      1       |           0            |    0   |   0    |

<a name="ex02"></a>
### 2-ші Тапсырма

Төменде көрсетілген `split_dataset()` функциясын келесі нұсқауларға сәйкес толықтырыңыз:

- `node_indices` тізіміндегі әрбір индекс үшін:
    - Егер `X` массивіндегі, сол индекс пен ерекшелік бойынша алынған мән `1` болса, сол индекс `left_indices` тізіміне қосыңыз
    - Егер `X` массивіндегі, сол индекс пен ерекшелік бойынша алынған мән `0` болса, сол индекс `right_indices` тізіміне қосыңыз

Егер қиындық туындаса, келесі ұяшықтан кейін берілген кеңестерді қарап, іске асыруға көмек алыңыз.

In [8]:
def split_dataset(X, node_indices, feature):
    """
    Берілген түйіндегі деректерді сол және оң тармақтарға бөледі

    Параметрлер:
        X (ndarray):          (n_samples, n_features) өлшеміндегі деректер матрицасы
        node_indices (list):  Қазіргі таңда қарастырылып отырған үлгілердің индекстер тізімі.
        feature (int):        Бөлуге қолданылатын ерекшеліктің индексі

    Қайтарылатын мәндер:
        left_indices (list):  Мәні == 1 болатын ерекшелік индекстері
        right_indices (list): Мәні == 0 болатын ерекшелік индекстері
    """

    # Төмендегі айнымалыларды дұрыс қайтаруыңыз қажет
    left_indices = []
    right_indices = []

    ### КОДТЫ ОСЫ ЖЕРДЕ БАСТАҢЫЗ ###


    ### КОДТЫ ОСЫ ЖЕРДЕ АЯҚТАҢЫЗ ###

    return left_indices, right_indices


Now, let's check your implementation using the code blocks below. Let's try splitting the dataset at the root node, which contains all examples at feature 0 (Brown Cap) as we'd discussed above

In [9]:
root_indices = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# Осы айнымалылармен еркін эксперимент жасаңыз
# Деректер жиынында тек үш ерекшелік бар, сондықтан бұл мән 0 (Қоңыр Қалпақ), 1 (Шырайлы Соққының Пішіні) немесе 2 (Жалғыз) болуы мүмкін
feature = 0

left_indices, right_indices = split_dataset(X_train, root_indices, feature)

print("Сол индекстер: ", left_indices)
print("Оң индекстер: ", right_indices)

# БӨЛІКТЕУ ТЕСТІ
split_dataset_test(split_dataset)


Сол индекстер:  [0, 1, 2, 3, 4, 7, 9]
Оң индекстер:  [5, 6, 8]
 All tests passed.


<a name="4.3"></a>
### 4.3  Ақпараттық пайданы есептеу

Келесі қадамда, сіз оқыту деректерін, түйіндегі индекстерді және бөлінетін ерекшелікті қабылдайтын, содан кейін бөлуден алынған ақпараттық пайданы қайтаратын `information_gain` деп аталатын функция жазасыз.

<a name="ex03"></a>
### 3-ші Тапсырма

Төменде берілген `compute_information_gain()` функциясын келесі формула бойынша есептеу үшін толықтырыңыз:

$$\text{Information Gain} = H(p_1^\text{node})- (w^{\text{left}}H(p_1^\text{left}) + w^{\text{right}}H(p_1^\text{right}))$$

мұнда:
- $H(p_1^\text{node})$ – түйіндегі энтропия
- $H(p_1^\text{left})$ және $H(p_1^\text{right})$ – бөлуден кейінгі сол және оң тармақтардағы энтропиялар
- $w^{\text{left}}$ және $w^{\text{right}}$ – сәйкесінше сол және оң тармақтардағы үлгілердің үлесі

Ескерту:
- Энтропияны есептеу үшін жоғарыда іске асырған `compute_entropy()` функциясын пайдалана аласыз
- Біз деректер жиынын бөлу үшін жоғарыда іске асырған `split_dataset()` функциясын қолданатын бастапқы кодты ұсындық

Егер қиындық туындаса, іске асыруға көмек беру үшін келесі ұяшықтағы кеңестерді қараңыз.

In [10]:
# Бағаланатын ФУНКЦИЯ: compute_information_gain

def compute_information_gain(X, y, node_indices, feature):
    """
    Берілген ерекшілік бойынша түйінді бөлу арқылы ақпараттық пайданы есептейді

    Параметрлер:
        X (ndarray):            (n_samples, n_features) өлшеміндегі деректер матрицасы
        y (array like):         n_samples мөлшеріндегі мақсатты айнымалыны қамтитын тізім немесе ndarray
        node_indices (ndarray): Осы қадамда қарастырылып отырған үлгілердің индекстер тізімі

    Қайтарылатын мән:
        cost (float):        Есептелген шығын (ақпараттық пайда)
    """
    # Деректер жиынын бөлу
    left_indices, right_indices = split_dataset(X, node_indices, feature)

    # Кейбір пайдалы айнымалылар
    X_node, y_node = X[node_indices], y[node_indices]
    X_left, y_left = X[left_indices], y[left_indices]
    X_right, y_right = X[right_indices], y[right_indices]

    # Төмендегі айнымалыларды дұрыс қайтаруыңыз қажет
    information_gain = 0

    ### КОДТЫ ОСЫ ЖЕРДЕ БАСТАҢЫЗ ###


    ### КОДТЫ ОСЫ ЖЕРДЕ АЯҚТАҢЫЗ ###

    return information_gain


Енді төмендегі ұяшықты пайдаланып іске асыруды тексеруге және мүмкіндіктердің әрқайсысына бөлуден алынған ақпараттың қандай болатынын есептей аласыз.

In [11]:
info_gain0 = compute_information_gain(X_train, y_train, root_indices, feature=0)
print("Түбірді қоңыр қалпақ бойынша бөлуден алынған ақпараттық пайда: ", info_gain0)

info_gain1 = compute_information_gain(X_train, y_train, root_indices, feature=1)
print("Түбірді шырайлы соққының пішіні бойынша бөлуден алынған ақпараттық пайда: ", info_gain1)

info_gain2 = compute_information_gain(X_train, y_train, root_indices, feature=2)
print("Түбірді жалғыз бойынша бөлуден алынған ақпараттық пайда: ", info_gain2)

# БӨЛІКТЕУ ТЕСТІ
compute_information_gain_test(compute_information_gain)


Түбірді қоңыр қалпақ бойынша бөлуден алынған ақпараттық пайда:  0.034851554559677034
Түбірді шырайлы соққының пішіні бойынша бөлуден алынған ақпараттық пайда:  0.12451124978365313
Түбірді жалғыз бойынша бөлуден алынған ақпараттық пайда:  0.2780719051126377
 All tests passed.


Түбірлік түйінде «Жалғыз» (мүмкіндік = 2) бойынша бөлу ақпараттың максималды пайдасын береді. Сондықтан, бұл түбірлік түйінде бөлуге болатын ең жақсы мүмкіндік.

<a name="4.4"></a>
### 4.4  Ең жақсы бөлуді анықтау

Енді әр ерекшелік бойынша ақпараттық пайданы есептеп, ең үлкен ақпараттық пайданы беретін ерекшелікті қайтарып беретін функция жазайық.

<a name="ex04"></a>
### 4-ші Тапсырма

Төменде берілген `get_best_split()` функциясын толықтырыңыз.
- Функция оқыту деректерін және түйіндегі үлгілердің индекстерін қабылдайды.
- Функцияның нәтижесінде ең үлкен ақпараттық пайданы беретін ерекшелік қайтарылады.
    - Әр ерекшелік үшін ақпараттық пайданы есептеу мақсатында `compute_information_gain()` функциясын пайдалана аласыз.
    
Егер қиындық туындаса, іске асыруға көмек беру үшін келесі ұяшықтағы кеңестерді қараңыз.

In [12]:
# UNQ_C4
# Бағаланатын ФУНКЦИЯ: get_best_split

def get_best_split(X, y, node_indices):
    """
    Түйіндегі деректерді бөлу үшін ең тиімді ерекшелік пен шекті мәнді қайтарады

    Параметрлер:
        X (ndarray):            (n_samples, n_features) өлшеміндегі деректер матрицасы
        y (array like):         Мақсатты айнымалыны қамтитын n_samples мөлшеріндегі тізім немесе ndarray
        node_indices (ndarray): Осы қадамда қарастырылып отырған үлгілердің индекстер тізімі

    Қайтарылатын мән:
        best_feature (int):     Бөлу үшін ең жақсы ерекшеліктің индексі
    """

    # Кейбір пайдалы айнымалылар
    num_features = X.shape[1]

    # Төмендегі айнымалыларды дұрыс қайтаруыңыз қажет
    best_feature = -1

    ### КОДТЫ ОСЫ ЖЕРДЕ БАСТАҢЫЗ ###


    ### КОДТЫ ОСЫ ЖЕРДЕ АЯҚТАҢЫЗ ###

    return best_feature

Енді төмендегі ұяшықты пайдаланып функцияңыздың орындалуын тексерейік.

In [13]:
best_feature = get_best_split(X_train, y_train, root_indices)
print("Бөлу үшін ең жақсы ерекшелік: %d" % best_feature)

# БӨЛІКТЕУ ТЕСТІ
get_best_split_test(get_best_split)

Бөлу үшін ең жақсы ерекшелік: 2
 All tests passed.


Жоғарыда көргеніміздей, функция түбірлік түйінде бөлуге болатын ең жақсы мүмкіндік 2-функция («Жалғыз») екенін қайтарады.

## Ағашты құру

Осы бөлімде жоғарыда іске асырған функцияларды пайдаланып, шешім ағашын құрамыз. Біз ең жақсы ерекшелікті таңдап, оны бөлуді тоқтау критерийіне жеткенше (максималды тереңдік 2) қайталаймыз.

Бұл бөлім үшін қосымша іске асыру қажет емес.

In [14]:
tree = []

def build_tree_recursive(X, y, node_indices, branch_name, max_depth, current_depth):
    """
    Рекурсивті алгоритмді қолданып, деректер жиынын әрбір түйінде 2 топқа бөлетін ағаш құру.
    Бұл функция тек ағашты басып шығарады.

    Параметрлер:
        X (ndarray):            (n_samples, n_features) өлшеміндегі деректер матрицасы
        y (array like):         n_samples мөлшеріндегі мақсатты айнымалыны қамтитын тізім немесе ndarray
        node_indices (ndarray): Осы қадамда қарастырылып отырған үлгілердің индекстер тізімі.
        branch_name (string):   Тармақтың атауы. ['Root', 'Left', 'Right']
        max_depth (int):        Құрылатын ағаштың максималды тереңдігі.
        current_depth (int):    Ағымдағы тереңдік. Рекурсивті шақыру кезінде қолданылатын параметр.
    """

    # Максималды тереңдікке жетті - бөлуді тоқтатыңыз
    if current_depth == max_depth:
        formatting = " " * current_depth + "-" * current_depth
        print(formatting, "%s жапырақты түйін, индекстері" % branch_name, node_indices)
        return

    # Әйтпесе, ең жақсы бөлуді табыңыз және деректерді бөліңіз
    # Осы түйіндегі ең жақсы ерекшелікті табыңыз
    best_feature = get_best_split(X, y, node_indices)
    tree.append((current_depth, branch_name, best_feature, node_indices))

    formatting = "-" * current_depth
    print("%s Тереңдік %d, %s: Бөлу, ерекшелік: %d" % (formatting, current_depth, branch_name, best_feature))

    # Деректер жиынын ең жақсы ерекшелік бойынша бөліңіз
    left_indices, right_indices = split_dataset(X, node_indices, best_feature)

    # Сол және оң ұрпақтарды бөлуді жалғастырыңыз. Ағымдағы тереңдікті арттырыңыз
    build_tree_recursive(X, y, left_indices, "Left", max_depth, current_depth + 1)
    build_tree_recursive(X, y, right_indices, "Right", max_depth, current_depth + 1)


In [15]:
build_tree_recursive(X_train, y_train, root_indices, "Root", max_depth=2, current_depth=0)

 Тереңдік 0, Root: Бөлу, ерекшелік: 2
- Тереңдік 1, Left: Бөлу, ерекшелік: 0
  -- Left жапырақты түйін, индекстері [0, 1, 4, 7]
  -- Right жапырақты түйін, индекстері [5]
- Тереңдік 1, Right: Бөлу, ерекшелік: 1
  -- Left жапырақты түйін, индекстері [8]
  -- Right жапырақты түйін, индекстері [2, 3, 6, 9]
